### ISSUE TITLE
Missing Textures and Gadget stops spinning upon teleporting

### ISSUE THREAD

**Issue by SDUBZ** [AtomicBlom/WeirdingGadget#1]
missing textures in and when placed
and unloads itself when gone 2000 blocks away

forge:1.11.2-2230

**Comment by AtomicBlom** [comment]
Hi @SDUBZ,

Finally got to the bottom of those issues. Turns out it didn't unload itself, but there was a client/server sync issue. It's been resolved using 0.1.6 on Curse which should be available shortly.

Regards,
Steven
