### ISSUE TITLE
[Suggestion] Limited chunkloaders per player

### ISSUE THREAD

**Issue by zwamdurkel** [AtomicBlom/WeirdingGadget#13]
Can you make it so a player can only have a limited number of chunkloaders active at a time (and also add a config option for it obviously). This function would be great for server owners like myself who like to limit the amount of chunkloaders a player can posses and thus limiting the amount of loaded chunks.

Please consider adding this function
- Zwam

**Comment by kreezxil** [comment]
I second thins. You should also add the bounty system to Github, I'd be willing to put a bounty on this feature.

**Comment by AtomicBlom** [comment]
I've been recommending that people restrict chunk loading using the `forgeChunkLoading.cfg` file.

Each chunk loader uses 1 ticket, so you can set a per-mod playerTicketCount to say, 20 to only allow 20 chunk loaders to be active on a player.
