### ISSUE TITLE
Weirding Gadget fell over

### ISSUE THREAD

**Issue by PCSpinner** [AtomicBlom/WeirdingGadget#14]
Forge 14.23.5.2768
Weirding Gadget 4.0.5

There seems to be an issue with the rendering in the latest update. The icon and the 3d model have tipped sideways so that the top is facing east, though the hit box is still placed where it should be. The antenna still spins around the y-axis, even though it is aligned with the x-axis.

https://imgur.com/a/Lejs9wB

**Comment by AtomicBlom** [comment]
... what in the....?

I'll try fix this soon.

**Comment by RedSnt** [comment]
I'm glad someone posted this, I was about to as well. Looks really weird lol. Doesn't seem to matter how you put it down either. ![LUL](https://i.imgur.com/jjGDM2j.gif)

MC v. 1.12.2
TWG v. 2.0.5
Forge v. 14.23.5.2796

**Comment by AtomicBlom** [comment]
2.0.13 should be approved on CurseForge shortly. I was not able to reproduce this issue explicitly, but the bugfix does include some rendering fixes, such as the black spinner and the 2D item transform in the item bar.

If it's still happening with this build, can you please provide more info about modpacks, other mods, any logs etc.

**Comment by RedSnt** [comment]
It's still doing it for me. But I made a new profile with the same MC version and Forge version as I had used previously with the bug and it's not longer there, so it must be one of the mods I'm using.  

One thing I've noticed is that the *icon* for TWG is also turned 90 on its side in the inventory and JEI like shown in PCSpinner's pictures when it doesn't work, but it's correctly positioned the right way up when it does work.  
Either way, it has to do with one of the mods we must be using. Personally I don't use a public pack, I just threw together a small pack of 108 mods I wanted to play with, but I'll try and narrow it down.

**Comment by RedSnt** [comment]
I've narrowed it down to "(ConnectedTexturesMod)[https://www.curseforge.com/minecraft/mc-mods/ctm]" on my end. Which seems to be required by (Chisel)[https://www.curseforge.com/minecraft/mc-mods/chisel].

**Comment by RedSnt** [comment]
Hm. It must be a mod that interacts with chisel somehow because when I deactivate chisel in my modpack (and therefore also ConnectedTexturesMod) TWG works correctly, but when I make a fresh profile and install I don't get the issue. Which makes it a lot harder to narrow down 🤔.

EDIT: It's bloody [FoamFix](https://www.curseforge.com/minecraft/mc-mods/foamfix-for-minecraft)!

**Comment by PCSpinner** [comment]
I've narrowed it down to 

CTM 0.3.3.22
foamfix 0.10.3
weirdinggadget 2.0.13

take any one of these out and it's fine

**Comment by RedSnt** [comment]
Yeah, or more precisely, Foamfix and TWG on their own are fine, but as soon as ConnectedTexturesMod is installed it all goes tits up.. Or sideways I suppose.

**Comment by PCSpinner** [comment]
Further testing:

Rolling CTM back to 0.3.2.20 fixes it, so the problem is related to their latest changes.

Setting client.wipeModelCache to false in FoamFix configs fixed ~~the base, but the antenna is still sideways, and its texture breaks.~~ the problem. I must not have reloaded the client the first time.

Rolling FoamFix back to 0.9.9.1 LAWFUL fixes it, ANARCHY version still goes sideways.

**Comment by RedSnt** [comment]
Setting "B:wipeModelCache" to false in Foamfix.cfg seems to fix the problem. And it took a looong time to reload minecraft that many times, I wish one could just reload configs on the fly, or maybe I'm missing a trick?

Anyway, here is the comment in the foamfix.cfg for that setting: 

`# Wipes the IModel cache after baking is finished. Saves a lot of RAM, as most IModels will not be reloaded. [default: true]`

So TWG reloads its IModel which cause the bug with CTG and Foamfix? Very specific bug indeed (but of course, mostly Foamfix' fault).

**Comment by AtomicBlom** [comment]
In that case, we might need to see if @asiekierka or @tterrag1098 have any ideas, perhaps they might have seen odd rotations before, but seeing as not every block in the pack is rotated there is probably some workaround or missing method that I haven't implemented.

**Comment by Stellerclive** [comment]
Has there been any progress on this issue It seems cosmetic but Is still present in the Skyfactory 4 modpack I was messing with today.

**Comment by AtomicBlom** [comment]
I finally made the time to "solve" the problem. It's a disgusting hack, but I've tested the following configurations and it seems to be working now:
* weirding gadget solo
* weirding gadget + foamfix anarchy
* weirding gadget + ctmlib 3.3
* weirding gadget + ctmlib 3.2
* weirding gadget + ctmlib 3.3 + foamfix anarchy + wipeModelCache enabled + core mods enabled
* weirding gadget + ctmlib 3.3 + foamfix anarchy + wipeModelCache disabled
* weirding gadget + ctmlib 3.3 + foamfix anarchy + core mods disabled

Please check out version 2.1.15 on https://minecraft.curseforge.com/projects/the-weirding-gadget/files and let me know if it's safe to move from alpha to release.
