### ISSUE TITLE
Plans for Fabric?

### ISSUE THREAD

**Issue by vico93** [AtomicBlom/WeirdingGadget#26]
I wonder if we can see someday this mod ported to Fabric (maybe starting from 1.17).

Personally i ditched Forge entirely due to performance issues (mostly when using worldgen changing mods and datapacks).

Thanks for this mod!

**Comment by AtomicBlom** [comment]
To be honest, it's highly unlikely at this point. Right now I'm focussed on a game I'm writing from scratch, and I only intend to port the mod forwards and fix bugs, I probably won't invest any time on features or investigating other frameworks for the foreseeable future.

If someone were to contribute a Fabric port of the mod, I'd happily review and probably see about maintaining it, but I won't be investing the time myself sorry.

**Comment by vico93** [comment]
Thanks for the info! I set a request on Fabric discord to see if someone have interest in PR/fork this mod.
