### ISSUE TITLE
Recipe missing 1.12.2

### ISSUE THREAD

**Issue by NicosaurusRex99** [AtomicBlom/WeirdingGadget#3]
Weirding gadget 1.12.2 doesnt have a recipe.
![2017-10-01_19 42 27](https://user-images.githubusercontent.com/11579935/31053254-ae3c375e-a6e0-11e7-822a-8164044f80cb.png)

**Comment by NicosaurusRex99** [comment]
![2017-10-01_19 42 59](https://user-images.githubusercontent.com/11579935/31053258-c0c245f8-a6e0-11e7-836f-7938824c7873.png)

**Comment by AtomicBlom** [comment]
Oh my g...

Of all the stupid things to forget to do... Fix incoming when I have a moment tonight.

**Comment by NicosaurusRex99** [comment]
LOL i made that mistake once myself :p

**Comment by AtomicBlom** [comment]
Fixed in 2.0.3
